### ISSUE TITLE
airtable-function directory?

### ISSUE THREAD

**Issue by Talii123** [Ekwuno/egghead-cloudflare-pages-site#1]
I think you forgot to check in this directory..

**Comment by Ekwuno** [comment]
Ah! Good catch. Thanks for checking out the course. I just fixed that.

**Comment by Ekwuno** [comment]
Hey @Talii123 I am so sorry I forgot to push the folder at first, do you mind re-writing your review on egghead. I would love to know what you thought about the course.

**Comment by Talii123** [comment]
I don't think I can change it. 
That said, I agreed with some of the feedback from one of the harsher reviews, though I don't agree with their (too!) low score. It could have benefited from some more context and organization. Perhaps some big picture diagram that explains how things fit together, and assumes the reader is new to more than just Cloudflare workers.

**Comment by Ekwuno** [comment]
Ah! I see. Thanks for the feedback, I structured this course to be an intro to What Cloudflare Pages can do for an existing site. 

Also to be honest, egghead courses are structured to answer a "How to" question. 

Do you have any specific parts where more context would have been helpful?
